### ISSUE TITLE
Create bag select/edit menus

### ISSUE THREAD

**Issue by igrad** [igrad/Bag-of-Holding#3]
## Task List: bagPick
Menu used to display all of the bags available to the user as well as a bit of information about each one.
- [x] Create widget layout/sizes
- [x] Create widget group
- [x] Create function to open menu
- [x] Create artwork for bagPick itself
- [x] (0%) Create artwork for list items
- [ ] *(Optional - likely) Change opening animation from jump-cut to slide-in*

## Task List: bagOpen
Submenu used to display options available for editing the selected bag.
- [x] Create widget layout/sizes
- [x] Create widget group
- [x] Implement back end code to open menu
- [x] Create background artwork
- [x] Create button artwork
- [ ] *(Optional - maybe) Menu option for setting a bag theme*

## Task List: bagWeight
Submenu used to change weight system implemented (metric or English (defaults to English)).
- [ ] (0%) Create widget layout/sizes
- [ ] (0%) Create widget group
- [ ] (0%) Implement function to save changes to bag's weight system

## Task List: bagCurrency
Submenu used to change currency system of a bag, including an unlimited number of currency types all related to a single base unit.
- [ ] (0%) Create widget layout/sizes
- [ ] (0%) Create widget group
- [ ] (0%) Implement function to save changes to bag's currency system

## Task List: bagCreate
Submenu for the user to input information about a bag being created, such as name, weight and currency systems, and possible (in the future) a bag theme.
- [ ] (0%) Create widget layout/sizes
- [ ] (0%) Create widget group
- [ ] (0%) Create background artwork
- [ ] (0%) Create button artwork
- [ ] *(Optional - maybe) Menu option for setting a bag theme*
