### ISSUE TITLE
Create itemOpts menus

### ISSUE THREAD

**Issue by igrad** [igrad/Bag-of-Holding#5]
## Task List: itemOpts
Menu containing options to move or delete an item within a bag.
- [x] Create widget layout/sizes
- [x] Create widget group
- [x] Create function to open/close menu
- [x] Create background artwork for menu
- [x] Create artwork for buttons

## Task List: itemMove
Menu containing options to move or delete an item within a bag.
- [x] Create widget layout/sizes
- [x] Create widget group
- [ ] Create function to open/close menu
- [x] Create background artwork for menu
- [ ] Create artwork for buttons in list

## Task List: itemDelete
Menu containing options to move or delete an item within a bag.
- [x] Create widget layout/sizes
- [x] Create widget group
- [ ] Create function to open menu
- [ ] Create background artwork for menu
- [ ] Create artwork for buttons
